# .github/workflows/ping-render.yml
name: Ping Render Apps

on:
  schedule:
    - cron: '00 * * * *'  # 13分おき（UTC時間）
    - cron: '10 * * * *'  # 13分おき（UTC時間）
    - cron: '20 * * * *'  # 13分おき（UTC時間）
    - cron: '30 * * * *'  # 13分おき（UTC時間）
    - cron: '40 * * * *'  # 13分おき（UTC時間）
    - cron: '50 * * * *'  # 13分おき（UTC時間）
    - cron: '*/8 * * * *'  # 13分おき（UTC

workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Apps and check status
        run: |
          SITES=(
            "https://webappnewtest0b.onrender.com/"
            "https://albummakefromgpt.onrender.com/"
          )

          for URL in "${SITES[@]}"; do
            echo "Pinging $URL ..."
            STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -m 10 "$URL" || echo "000")
            echo "Status Code: $STATUS_CODE"

            if [ "$STATUS_CODE" != "200" ]; then
              echo "Warning: $URL may not have responded successfully (HTTP $STATUS_CODE)"
            fi
            echo ""
          done
